import {
  EmbedBuilder,
  ButtonBuilder,
  ActionRowBuilder,
  ButtonStyle,
} from "discord.js";
import { EmbedBuilderWithComponents } from "./types";
import { environment } from "../config/environment";

export function createDownloadEmbed(
  downloadURL: string
): EmbedBuilderWithComponents {
  const embed = new EmbedBuilder()
    .setTitle("🎵 Your audio file is ready!")
    .setDescription(
      `Click the button below to download your audio. Enjoy listening! 🎧`
    )
    .setColor("#0099ff")
    .setThumbnail(
      "https://firebasestorage.googleapis.com/v0/b/yt-audio-downloader.appspot.com/o/logos%2Fyt-downloader-thumb.png?alt=media&token=5407d0df-0d31-4cd7-a9c0-88cdd83faee2"
    ) // Replace with a relevant image URL
    .setFooter({
      text: "Generated by YT Downloader",
      iconURL:
        "https://firebasestorage.googleapis.com/v0/b/yt-audio-downloader.appspot.com/o/logos%2Fyt-downloader-logo.png?alt=media&token=a30b0218-9638-4e8d-9300-f19a43d51704",
    }) // Replace with your bot's name and icon URL
    .setTimestamp();

  const fileUrl = encodeURIComponent(downloadURL);
  const downloadButtonUrl = fileUrl;

  const downloadButton = new ButtonBuilder()
    .setStyle(ButtonStyle.Link)
    .setURL(downloadButtonUrl)
    .setLabel("Download Audio")
    .setEmoji("🔽");

  const row = new ActionRowBuilder().addComponents(downloadButton);

  return {
    embeds: [embed],
    components: [row],
  };
}
